// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProbForm.DBContext;

namespace ProbForm.DBContext.Migrations
{
    [DbContext(typeof(ProbFormDBContext))]
    [Migration("20190308080327_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("ProbForm.Models.Match", b =>
                {
                    b.Property<int>("Day");

                    b.Property<string>("HomeTeamId")
                        .HasMaxLength(50);

                    b.Property<string>("AwayTeamId")
                        .HasMaxLength(50);

                    b.Property<string>("AwayModule");

                    b.Property<string>("HomeModule");

                    b.Property<DateTime>("MatchTime");

                    b.HasKey("Day", "HomeTeamId", "AwayTeamId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("ProbForm.Models.Player", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("TeamId")
                        .HasMaxLength(50);

                    b.Property<string>("Number");

                    b.HasKey("Name", "TeamId");

                    b.HasAlternateKey("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ProbForm.Models.Team", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("Mister");

                    b.HasKey("Name");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ProbForm.Models.TeamPlayer", b =>
                {
                    b.Property<int>("TeamPlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Info");

                    b.Property<int>("Order");

                    b.Property<int>("Status");

                    b.Property<string>("TeamName");

                    b.Property<string>("playerName");

                    b.Property<string>("playerTeamId");

                    b.HasKey("TeamPlayerId");

                    b.HasIndex("TeamName");

                    b.HasIndex("playerName", "playerTeamId");

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("ProbForm.Models.Match", b =>
                {
                    b.HasOne("ProbForm.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProbForm.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProbForm.Models.TeamPlayer", b =>
                {
                    b.HasOne("ProbForm.Models.Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamName");

                    b.HasOne("ProbForm.Models.Player", "player")
                        .WithMany()
                        .HasForeignKey("playerName", "playerTeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
