// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProbForm.DBContext;

namespace ProbForm.DBContext.Migrations
{
    [DbContext(typeof(ProbFormDBContext))]
    [Migration("20190305233207_add_PK")]
    partial class add_PK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("ProbForm.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AwayTeamTeamId");

                    b.Property<int?>("HomeTeamTeamId");

                    b.Property<DateTime>("MatchTime");

                    b.HasKey("MatchId");

                    b.HasIndex("AwayTeamTeamId");

                    b.HasIndex("HomeTeamTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("ProbForm.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Number");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ProbForm.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Mister");

                    b.Property<string>("Module");

                    b.Property<string>("Name");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ProbForm.Models.TeamPlayer", b =>
                {
                    b.Property<int>("TeamPlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Info");

                    b.Property<int>("Order");

                    b.Property<int?>("PlayerId");

                    b.Property<int>("Status");

                    b.Property<int?>("TeamId");

                    b.HasKey("TeamPlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("ProbForm.Models.Match", b =>
                {
                    b.HasOne("ProbForm.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamTeamId");

                    b.HasOne("ProbForm.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamTeamId");
                });

            modelBuilder.Entity("ProbForm.Models.TeamPlayer", b =>
                {
                    b.HasOne("ProbForm.Models.Player", "player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("ProbForm.Models.Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
